services:
  - type: web
    name: job-seeker-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: FRONTEND_URL
        value: https://your-frontend-site.netlify.app
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: COOKIE_EXPIRE
        value: 5
      - key: CLOUDINARY_CLIENT_NAME
        sync: false
      - key: CLOUDINARY_CLIENT_API
        sync: false
      - key: CLOUDINARY_CLIENT_SECRET
        sync: false
